### ISSUE TITLE
timeout.t hangs on Linux

### ISSUE THREAD

**Issue by chorny** [renatocron/WWW--Correios--CEP#4]
Perl 5.16.2 and 5.17.7.

perl -Mblib t/timeout.t 
1..3
ok 1 - use WWW::Correios::CEP;
ok 2 - WWW::Correios::CEP class ok

**Comment by renatocron** [comment]
It started hanging again with v5.20.3 and LWP::UserAgent 6.5

I changed the code to use alarm instead of trusting the UA.
